//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMForm
    {
        public CRMForm()
        {
            this.CRMScrores = new HashSet<CRMScrore>();
        }
    
        public int Id { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ICollection<CRMScrore> CRMScrores { get; set; }
    }
}
