//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMTemplate
    {
        public CRMTemplate()
        {
            this.CRMScrores = new HashSet<CRMScrore>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public int ServiceCategory { get; set; }
        public int ServiceType { get; set; }
    
        public virtual ICollection<CRMScrore> CRMScrores { get; set; }
        public virtual CRMServiceCategory CRMServiceCategory { get; set; }
        public virtual CRMServiceType CRMServiceType { get; set; }
    }
}
