//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PostcalCode { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string ReferencePerson { get; set; }
        public string ReferenceEmail { get; set; }
        public string ReferencePhoneNumber { get; set; }
        public string CustomerTitle { get; set; }
        public string CustomerSurname { get; set; }
        public string CoupleTitle { get; set; }
        public string CoupleName { get; set; }
        public string CoupleSurname { get; set; }
        public string CouplePhoneNumber { get; set; }
        public string BuildingBlock { get; set; }
        public string Road { get; set; }
        public string Subdistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string CoupleEmail { get; set; }
        public string ReferenceTitle { get; set; }
        public string ReferenceSurname { get; set; }
        public string CustomerNickname { get; set; }
        public string CoupleNickname { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
