//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionSatisfaction
    {
        public DimensionSatisfaction()
        {
            this.PerformanceFacts = new HashSet<PerformanceFacts>();
        }
    
        public int SatisfactionId { get; set; }
        public Nullable<int> BestScore { get; set; }
        public Nullable<int> WorseScore { get; set; }
    
        public virtual ICollection<PerformanceFacts> PerformanceFacts { get; set; }
    }
}
