//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionTime
    {
        public DimensionTime()
        {
            this.PerformanceFacts = new HashSet<PerformanceFacts>();
        }
    
        public int TimeId { get; set; }
        public string Year { get; set; }
        public string Quarter { get; set; }
        public string Month { get; set; }
    
        public virtual ICollection<PerformanceFacts> PerformanceFacts { get; set; }
    }
}
