//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeClaims = new HashSet<EmployeeClaim>();
            this.EmployeeLogins = new HashSet<EmployeeLogin1>();
            this.EmployeeRoles = new HashSet<EmployeeRole>();
        }
    
        public string EmployeeId { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Discriminator { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdentificationNumber { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public string Specialability { get; set; }
    
        public virtual ICollection<EmployeeClaim> EmployeeClaims { get; set; }
        public virtual ICollection<EmployeeLogin1> EmployeeLogins { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}
