//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCStudioDWEntities : DbContext
    {
        public NCStudioDWEntities()
            : base("name=NCStudioDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimensionPhotoGrapher> DimensionPhotoGrapher { get; set; }
        public virtual DbSet<DimensionPromotion> DimensionPromotion { get; set; }
        public virtual DbSet<DimensionSatisfaction> DimensionSatisfaction { get; set; }
        public virtual DbSet<DimensionTime> DimensionTime { get; set; }
        public virtual DbSet<PerformanceFacts> PerformanceFacts { get; set; }
        public virtual DbSet<DimensionServiceType> DimensionServiceType { get; set; }
    }
}
