//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputSchedule
    {
        public int Id { get; set; }
        public string PackageName { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public System.DateTime HandOnDate { get; set; }
        public Nullable<System.DateTime> ReviseDate { get; set; }
        public Nullable<int> ReviseCount { get; set; }
        public int OutputServiceId { get; set; }
        public int OutputQuantity { get; set; }
    
        public virtual ServiceForm ServiceForm { get; set; }
        public virtual OutputStatu OutputStatu { get; set; }
    }
}
