//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourceServiceType
    {
        public OutsourceServiceType()
        {
            this.OutsourceContacts = new HashSet<OutsourceContact>();
            this.OutSourcePriceRanges = new HashSet<OutSourcePriceRanx>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<OutsourceContact> OutsourceContacts { get; set; }
        public virtual ICollection<OutSourcePriceRanx> OutSourcePriceRanges { get; set; }
    }
}
