//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourceContact
    {
        public OutsourceContact()
        {
            this.OutsourceServices = new HashSet<OutsourceService>();
        }
    
        public int OutsourceContactId { get; set; }
        public string OutsourceName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public System.TimeSpan OpenTime { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public string Detail { get; set; }
    
        public virtual OutsourceServiceType OutsourceServiceType { get; set; }
        public virtual OutsourceStatu OutsourceStatu { get; set; }
        public virtual ICollection<OutsourceService> OutsourceServices { get; set; }
    }
}
