//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutSourcePriceRanx
    {
        public int Id { get; set; }
        public string RangeName { get; set; }
        public int MinRange { get; set; }
        public int MaxRange { get; set; }
    
        public virtual OutsourceServiceType OutsourceServiceType { get; set; }
    }
}
