//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceFacts
    {
        public int TimeId { get; set; }
        public int PromotionId { get; set; }
        public int SatisfactionId { get; set; }
        public int PhotoGrapherId { get; set; }
        public int ServiceTypeId { get; set; }
        public Nullable<int> ApprisalScore { get; set; }
        public Nullable<decimal> ProfitPercent { get; set; }
        public Nullable<int> SaleAmount { get; set; }
        public Nullable<int> CostAmount { get; set; }
    
        public virtual DimensionPhotoGrapher DimensionPhotoGrapher { get; set; }
        public virtual DimensionPromotion DimensionPromotion { get; set; }
        public virtual DimensionSatisfaction DimensionSatisfaction { get; set; }
        public virtual DimensionTime DimensionTime { get; set; }
        public virtual DimensionServiceType DimensionServiceType { get; set; }
    }
}
