//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int PhotoGraphDiscount { get; set; }
        public int EquipmentDiscount { get; set; }
        public int LocationDiscount { get; set; }
        public int OutputDiscount { get; set; }
        public int OutsourceDiscount { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
