//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.EmployeeRoles = new HashSet<EmployeeRole>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}
