//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.ServiceForms = new HashSet<ServiceForm>();
        }
    
        public int Id { get; set; }
        public string ServiceTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ServiceForm> ServiceForms { get; set; }
    }
}
