//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePictureStudio.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Bookings = new HashSet<Booking>();
            this.ServiceForms = new HashSet<ServiceForm>();
        }
    
        public int Id { get; set; }
        public string BookingName { get; set; }
        public string GroomName { get; set; }
        public string BrideName { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<int> CRMFormId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ServiceForm> ServiceForms { get; set; }
        public virtual ServiceStatu ServiceStatu { get; set; }
    }
}
